# Generated by Django 3.2 on 2021-05-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'کاربرهای وبسایت'},
        ),
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(default='', max_length=40, verbose_name='نام کاربری'),
        ),
    ]
