# Generated by Django 3.2 on 2021-06-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAPI', '0002_auto_20210529_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
