# Generated by Django 3.2 on 2021-06-05 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loginAPI', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
