# Generated by Django 3.2 on 2021-06-05 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginAPI', '0005_book_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loginAPI.users'),
        ),
    ]
