# Generated by Django 3.2 on 2021-06-13 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginAPI', '0008_alter_book_author_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_one',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='one_rel', to='loginAPI.users'),
        ),
    ]
