# Generated by Django 3.2 on 2021-06-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginAPI', '0009_alter_book_author_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_one',
        ),
    ]
