# Generated by Django 3.2 on 2021-06-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAPI', '0012_book_brand_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='manyfield',
            field=models.ManyToManyField(related_name='many', to='loginAPI.Users'),
        ),
    ]
