# Generated by Django 3.2 on 2021-06-13 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginAPI', '0013_book_manyfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='brand_one',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='one_rel', to='loginAPI.brands'),
        ),
    ]
