# Generated by Django 3.2 on 2021-06-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAPI', '0014_alter_book_brand_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cofirm',
            field=models.CharField(choices=[('T', 'تایید شده'), ('N', 'تایید نشده'), ('P', 'منتظر تایید')], default='P', max_length=30),
        ),
    ]
