# Generated by Django 3.2 on 2021-08-01 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loginAPI', '0015_book_cofirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(default='no comment', max_length=500)),
            ],
        ),
    ]
