# Generated by Django 3.2 on 2021-08-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAPI', '0017_comment_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_valid_key',
            field=models.CharField(default='0', max_length=6),
        ),
    ]
